ALTER TABLE products
ADD COLUMN IF NOT EXISTS product_type VARCHAR(255);

ALTER TABLE products
ADD COLUMN IF NOT EXISTS size VARCHAR(255);

ALTER TABLE products
ADD COLUMN IF NOT EXISTS scent TEXT;

ALTER TABLE products
ADD COLUMN IF NOT EXISTS ingredients TEXT[];