// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skybfzbmpaibfvvydioh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNreWJmemJtcGFpYmZ2dnlkaW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjkzODAsImV4cCI6MjA2NDk0NTM4MH0.miORg06ya0aKrK4jVPhdn-ldwUl8EhwQ0TpHkYoLc2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);